(() => {
"use strict";
const $=id=>document.getElementById(id), qsa=s=>[...document.querySelectorAll(s)];
const S={media:null,url:null,kind:null,files:[],subtitles:[],activeSubtitle:null,subtitleOffset:0,subtitleOriginal:new Map(),queue:[],queueIndex:0,repeat:'off',repeatOnceUsed:false,audio:'original',video:'original',fit:'original',cc:'off',toast:null,playbackRate:1,controlsTimer:null,sourceMap:new Map(),audioCtx:null,remote:false,remoteProvider:null,remoteUrl:null,pipActive:false,weather:null,iosNative:false,hls:null};
const e={welcome:$('welcome'),greeting:$('greeting'),player:$('player'),shell:$('mediaShell'),prep:$('preparing'),stage:$('mediaStage'),backdrop:$('stageBackdrop'),empty:$('emptyStage'),audioVisual:$('audioVisual'),audioTitle:$('audioTitle'),video:$('video'),audio:$('audio'),image:$('image'),remote:$('remoteStage'),open:$('openBtn'),hero:$('heroOpenBtn'),url:$('urlBtn'),heroUrl:$('heroUrlBtn'),urlModal:$('urlModal'),urlInput:$('urlInput'),urlPlay:$('urlPlay'),urlCancel:$('urlCancel'),urlClose:$('urlClose'),subtitleModal:$('subtitleModal'),subtitleClose:$('subtitleClose'),subtitleChoose:$('subtitleChoose'),subtitleOnline:$('subtitleOnline'),subtitleProviders:$('subtitleProviders'),subtitleSync:$('subtitleSync'),syncTrackName:$('syncTrackName'),syncOffset:$('syncOffset'),syncMinus1:$('syncMinus1'),syncMinus01:$('syncMinus01'),syncReset:$('syncReset'),syncPlus01:$('syncPlus01'),syncPlus1:$('syncPlus1'),loadSub:$('loadSubBtn'),input:$('fileInput'),subInput:$('subtitleInput'),home:$('homeBtn'),play:$('playBtn'),back:$('backBtn'),forward:$('forwardBtn'),mute:$('muteBtn'),speedTop:$('speedTopBtn'),speedTopLabel:$('speedTopLabel'),seek:$('seek'),cur:$('currentTime'),dur:$('duration'),sound:$('audioModeBtn'),picture:$('videoModeBtn'),close:$('closeBtn'),prev:$('prevBtn'),stop:$('stopBtn'),next:$('nextBtn'),repeat:$('repeatBtn'),muteLabel:$('muteLabel'),repeatLabel:$('repeatLabel'),fit:$('fitBtn'),pip:$('pipBtn'),full:$('fullscreenBtn'),toast:$('modeToast'),toastIcon:$('modeToastIcon'),toastType:$('modeToastType'),toastText:$('modeToastText'),topActions:$('topActions'),weather:$('weatherLayer'),weatherAttribution:$('weatherAttribution')};

function greeting(){const h=new Date().getHours();return h<5?'Good Night':h<12?'Good Morning':h<17?'Good Afternoon':h<21?'Good Evening':'Good Night'}
e.greeting.textContent=greeting();setInterval(()=>e.greeting.textContent=greeting(),60000);
function ambientClass(level){document.body.classList.remove('ambient-bright','ambient-dim','ambient-night');document.body.classList.add('ambient-'+level)}
function clearWeatherLayer(){if(e.weather)e.weather.innerHTML='';e.weather?.classList.remove('rain','storm','snow','clouds','clear');e.weatherAttribution?.classList.add('hidden')}
function weatherVisual(code){
  clearWeatherLayer();
  if(code===0){e.weather?.classList.add('clear');return 'clear'}
  if(code>=1&&code<=3){e.weather?.classList.add('clouds');return 'clouds'}
  if((code>=51&&code<=67)||(code>=80&&code<=82)){e.weather?.classList.add('rain');for(let i=0;i<42;i++){const d=document.createElement('i');d.style.setProperty('--x',Math.random()*100+'%');d.style.setProperty('--d',(0.45+Math.random()*0.9)+'s');d.style.setProperty('--delay',(Math.random()*1.4)+'s');d.style.setProperty('--len',(10+Math.random()*18)+'px');e.weather.appendChild(d)}return 'rain'}
  if((code>=71&&code<=77)||(code>=85&&code<=86)){e.weather?.classList.add('snow');for(let i=0;i<34;i++){const d=document.createElement('i');d.style.setProperty('--x',Math.random()*100+'%');d.style.setProperty('--d',(3+Math.random()*5)+'s');d.style.setProperty('--delay',(Math.random()*3)+'s');d.style.setProperty('--size',(2+Math.random()*4)+'px');e.weather.appendChild(d)}return 'snow'}
  if(code>=95){e.weather?.classList.add('storm');for(let i=0;i<48;i++){const d=document.createElement('i');d.style.setProperty('--x',Math.random()*100+'%');d.style.setProperty('--d',(0.35+Math.random()*0.65)+'s');d.style.setProperty('--delay',(Math.random()*1.5)+'s');d.style.setProperty('--len',(12+Math.random()*20)+'px');e.weather.appendChild(d)}return 'storm'}
  e.weather?.classList.add('clouds');return 'clouds'
}
async function loadWeather(){
  if(!navigator.geolocation)return;
  navigator.geolocation.getCurrentPosition(async pos=>{
    try{const {latitude,longitude}=pos.coords;const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${latitude}&longitude=${longitude}&current=weather_code,precipitation,rain,snowfall,cloud_cover&timezone=auto`);if(!r.ok)return;const j=await r.json();const c=Number(j.current?.weather_code);if(!Number.isFinite(c))return;S.weather=j.current;const mode=weatherVisual(c);document.body.dataset.weather=mode;e.weatherAttribution?.classList.remove('hidden')}catch{}
  },()=>{}, {enableHighAccuracy:false,maximumAge:900000,timeout:5000});
}
function initAmbientAdaptation(){const h=new Date().getHours();ambientClass(h>=21||h<5?'night':h<9||h>=18?'dim':'bright');if('AmbientLightSensor' in window){try{const sensor=new AmbientLightSensor({frequency:1});sensor.addEventListener('reading',()=>{const lux=sensor.illuminance;ambientClass(lux>180?'bright':lux>35?'dim':'night')});sensor.start()}catch{}}loadWeather()}
initAmbientAdaptation();
function showMode(type,text,icon){e.toastType.textContent=type;e.toastText.textContent=text;e.toastIcon.textContent=icon||'•';e.toast.classList.add('show');clearTimeout(S.toast);S.toast=setTimeout(()=>e.toast.classList.remove('show'),1700)}
function setMediaSessionMetadata(title='Foldrone Play'){try{if(!('mediaSession' in navigator)||typeof MediaMetadata==='undefined')return;navigator.mediaSession.metadata=new MediaMetadata({title,artist:'Foldrone Play',album:'Foldrone Media Core',artwork:[{src:'./header-logo-new.png',sizes:'2172x724',type:'image/png'}]})}catch{}}
function fmt(v){if(!Number.isFinite(v)||v<0)return'0:00';let s=Math.floor(v),h=Math.floor(s/3600),m=Math.floor(s%3600/60),x=s%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(x).padStart(2,'0')}`:`${m}:${String(x).padStart(2,'0')}`}
function kind(f){let t=(f.type||'').toLowerCase(),n=(f.name||'').toLowerCase();if(t.startsWith('video/')||/\.(mp4|m4v|webm|mov|ogv|avi|mkv|ts|m2ts)$/i.test(n))return'video';if(t.startsWith('audio/')||/\.(mp3|wav|flac|m4a|aac|ogg|opus|aiff)$/i.test(n))return'audio';if(t.startsWith('image/')||/\.(jpg|jpeg|png|gif|webp|avif|bmp|svg)$/i.test(n))return'image';if(/\.(srt|vtt|ass|ssa)$/i.test(n))return'subtitle'}
function activeMedia(){return S.media}
function isIOSLike(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||(/Macintosh/.test(navigator.userAgent)&&navigator.maxTouchPoints>1)}
S.iosNative=isIOSLike();if(navigator.audioSession){try{navigator.audioSession.type='playback'}catch{}}
function currentSource(){return S.media&&S.sourceMap.get(S.media)}
function disconnectGraph(srcObj){if(!srcObj)return;for(const n of [srcObj.source,srcObj.input,srcObj.comp,srcObj.pan,srcObj.output]){try{n?.disconnect()}catch{}}}
function ensureAudioGraph(mediaEl){if(S.iosNative)return null;const Ctx=window.AudioContext||window.webkitAudioContext;if(!Ctx||!mediaEl)return null;let g=S.sourceMap.get(mediaEl);if(g)return g;try{if(!S.audioCtx)S.audioCtx=new Ctx({latencyHint:'interactive'});const source=S.audioCtx.createMediaElementSource(mediaEl),input=S.audioCtx.createGain(),low=S.audioCtx.createBiquadFilter(),high=S.audioCtx.createBiquadFilter(),comp=S.audioCtx.createDynamicsCompressor(),output=S.audioCtx.createGain();low.type='lowshelf';low.frequency.value=120;high.type='highshelf';high.frequency.value=4200;source.connect(input).connect(low).connect(high).connect(comp).connect(output).connect(S.audioCtx.destination);g={source,input,low,high,comp,output};S.sourceMap.set(mediaEl,g);return g}catch{return null}}
function disconnectGraph(srcObj){if(!srcObj)return;for(const n of [srcObj.source,srcObj.input,srcObj.low,srcObj.high,srcObj.comp,srcObj.output]){try{n?.disconnect()}catch{}}}
function routeAudio(mode){if(S.iosNative){if(S.media){S.media.muted=false;S.media.volume=1}return true}const g=currentSource();if(!g||!S.audioCtx)return false;try{for(const n of [g.source,g.input,g.low,g.high,g.comp,g.output]){try{n.disconnect()}catch{}}g.input.gain.value=1;g.low.gain.value=0;g.high.gain.value=0;g.comp.threshold.value=-18;g.comp.knee.value=18;g.comp.ratio.value=2;g.comp.attack.value=.003;g.comp.release.value=.15;g.output.gain.value=1;if(mode==='original'){g.source.connect(g.output).connect(S.audioCtx.destination)}else{const cfg={enhanced:{gain:1.42,low:2.5,high:3.2,ratio:4.0,threshold:-23},cinema:{gain:1.28,low:5.0,high:2.5,ratio:3.5,threshold:-26},spatial:{gain:1.22,low:3.0,high:4.0,ratio:3.0,threshold:-22}}[mode]||{gain:1,low:0,high:0,ratio:2,threshold:-18};g.input.gain.value=cfg.gain;g.low.gain.value=cfg.low;g.high.gain.value=cfg.high;g.comp.threshold.value=cfg.threshold;g.comp.ratio.value=cfg.ratio;g.source.connect(g.input).connect(g.low).connect(g.high).connect(g.comp).connect(g.output).connect(S.audioCtx.destination)}S.audioCtx.resume().catch(()=>{});return true}catch{return false}}
function clearCurrentMedia(){S.hls?.destroy?.();S.hls=null;[e.video,e.audio].forEach(v=>{try{v.pause()}catch{};v.removeAttribute('src');try{v.load()}catch{};v.classList.add('hidden')});e.image.removeAttribute('src');e.image.classList.add('hidden');e.remote.innerHTML='';e.remote.classList.add('hidden');e.backdrop.style.backgroundImage='';e.audioVisual?.classList.add('hidden');e.audioVisual?.setAttribute('aria-hidden','true');S.url&&URL.revokeObjectURL(S.url);S.url=null;S.media=null;S.kind=null;S.subtitles=[];S.activeSubtitle=null;S.subtitleOffset=0;S.subtitleOriginal=new Map();S.cc='off';[...e.video.textTracks].forEach(t=>t.mode='disabled');e.empty.classList.remove('hidden');e.prep.classList.add('hidden');e.topActions.classList.add('hidden');e.shell.classList.remove('controls-hidden');e.video.style.filter='none';resetFrame(false);e.seek.value=0;e.seek.max=0;e.cur.textContent='0:00';e.dur.textContent='0:00'}
function clean(){clearCurrentMedia();S.remote=false;S.remoteProvider=null;S.remoteUrl=null;S.hls?.destroy?.();S.hls=null;S.files=[];S.queue=[];S.queueIndex=0;S.repeat='off';S.repeatOnceUsed=false;S.audio='original';S.video='original';S.fit='original';S.playbackRate=1;e.empty.classList.remove('hidden');updateLabels();updateTransportLabels()}
function openPicker(){e.input.value='';e.input.click()}
function resetFrame(show=true){S.fit='original';if(S.kind==='video'){e.video.classList.remove('fit-screen','fit-fill','fit-wide');e.video.style.transform=''}if(show)showMode('Screen Width','Original','↔')}
function applyFrame(){if(S.kind!=='video')return;e.video.classList.remove('fit-screen','fit-fill','fit-wide');if(S.fit==='fit')e.video.classList.add('fit-screen');if(S.fit==='fill')e.video.classList.add('fit-fill');if(S.fit==='wide')e.video.classList.add('fit-wide')}
function sync(){if(!S.media||S.remote)return;e.seek.max=Number.isFinite(S.media.duration)?S.media.duration:0;e.seek.value=S.media.currentTime||0;e.cur.textContent=fmt(S.media.currentTime);e.dur.textContent=fmt(S.media.duration)}
function bind(v){v.addEventListener('loadedmetadata',sync);v.addEventListener('timeupdate',sync);v.addEventListener('durationchange',sync);v.addEventListener('play',()=>{if(navigator.audioSession){try{navigator.audioSession.type='playback'}catch{}}e.play.innerHTML='<span class="i-pause"></span>';scheduleControlsHide()});v.addEventListener('pause',()=>{e.play.innerHTML='<span class="i-play"></span>';showControls()});v.addEventListener('ended',()=>{e.play.innerHTML='<span class="i-replay"></span>';if(S.repeat==='one'&&!S.repeatOnceUsed){S.repeatOnceUsed=true;v.currentTime=0;v.play().catch(()=>{})}else if(S.repeat==='track'){v.currentTime=0;v.play().catch(()=>{})}else if(S.repeat==='all'&&S.queue.length>1){nextTrack()}else{S.repeatOnceUsed=false}});v.addEventListener('volumechange',()=>{e.mute.innerHTML=v.muted?'<span class="i-volume-off"></span>':'<span class="i-volume"></span>';e.mute.title=v.muted?'Unmute':'Mute';e.mute.setAttribute('aria-label',v.muted?'Unmute':'Mute')});v.addEventListener('ratechange',()=>{S.playbackRate=v.playbackRate;updateSpeedLabel()})}
bind(e.video);bind(e.audio);
e.video.addEventListener('enterpictureinpicture',()=>{S.pipActive=true;S.audioCtx?.resume().catch(()=>{});showMode('PiP','Playback continues outside the browser','▣')});
e.video.addEventListener('leavepictureinpicture',()=>{S.pipActive=false;S.audioCtx?.resume().catch(()=>{})});
document.addEventListener('visibilitychange',()=>{if(S.pipActive||document.visibilityState==='visible')S.audioCtx?.resume().catch(()=>{})});
e.video.addEventListener('webkitpresentationmodechanged',()=>{const mode=e.video.webkitPresentationMode;if(mode==='picture-in-picture'){S.pipActive=true;S.audioCtx?.resume().catch(()=>{})}else{S.pipActive=false}});


function captureSubtitleTiming(track){
  if(!track||S.subtitleOriginal.has(track)||!track.cues)return;
  S.subtitleOriginal.set(track,[...track.cues].map(c=>({a:c.startTime,b:c.endTime})));
}
function activeSubtitleEntry(){
  const showing=[...e.video.textTracks].find(t=>(t.kind==='subtitles'||t.kind==='captions')&&t.mode==='showing');
  if(!showing)return null;
  captureSubtitleTiming(showing);
  return S.subtitles.find(s=>s.track===showing)||{track:showing,label:showing.label||showing.language||'Subtitle'};
}
function formatOffset(v){return `${v>=0?'+':''}${v.toFixed(1)}s`}
function updateSubtitleSyncUI(){
  const entry=activeSubtitleEntry();
  if(!entry||!e.subtitleSync)return;
  e.subtitleSync.classList.remove('hidden');
  e.syncTrackName.textContent=entry.label||entry.track?.label||'Subtitle timing';
  e.syncOffset.textContent=formatOffset(S.subtitleOffset);
}
function applySubtitleTiming(){
  const entry=activeSubtitleEntry();
  if(!entry?.track)return;
  captureSubtitleTiming(entry.track);
  const original=S.subtitleOriginal.get(entry.track);
  if(!original)return;
  const d=S.subtitleOffset;
  const cues=entry.track.cues||[];
  for(let i=0;i<cues.length;i++){
    const cue=cues[i],base=original[i];
    if(!cue||!base)continue;
    try{cue.startTime=Math.max(0,base.a+d);cue.endTime=Math.max(cue.startTime+.01,base.b+d)}catch{}
  }
  updateSubtitleSyncUI();
}
function setSubtitleOffset(delta){
  const entry=activeSubtitleEntry();
  if(!entry)return;
  S.subtitleOffset=Math.max(-30,Math.min(30,Math.round((S.subtitleOffset+delta)*10)/10));
  applySubtitleTiming();
  showMode('CC Sync',formatOffset(S.subtitleOffset),'CC+');
}
function resetSubtitleOffset(){
  const entry=activeSubtitleEntry();
  if(!entry)return;
  S.subtitleOffset=0;
  applySubtitleTiming();
  showMode('CC Sync','0.0s · Reset','CC+');
}
function parseSRT(text){text=text.replace(/\r/g,'').replace(/^\uFEFF/,'');let blocks=text.split(/\n{2,}/),out=[];for(const b of blocks){const lines=b.split('\n').filter(Boolean),i=lines.findIndex(x=>x.includes('-->'));if(i<0)continue;let m=lines[i].match(/(\d{1,2}):(\d{2}):(\d{2})[,.](\d{3})\s*-->\s*(\d{1,2}):(\d{2}):(\d{2})[,.](\d{3})/);if(m)out.push({a:+m[1]*3600+ +m[2]*60+ +m[3]+ +m[4]/1000,b:+m[5]*3600+ +m[6]*60+ +m[7]+ +m[8]/1000,t:lines.slice(i+1).join('\n')});else{m=lines[i].match(/(\d{2}):(\d{2})[,.](\d{3})\s*-->\s*(\d{2}):(\d{2})[,.](\d{3})/);if(m)out.push({a:+m[1]*60+ +m[2]+ +m[3]/1000,b:+m[4]*60+ +m[5]+ +m[6]/1000,t:lines.slice(i+1).join('\n')})}}return out}
function guessLang(name){let n=name.toLowerCase();if(/(^|[._-])(si|sin|sinhala)([._-]|$)/.test(n))return'si';if(/(^|[._-])(ta|tam|tamil)([._-]|$)/.test(n))return'ta';if(/(^|[._-])(en|eng|english)([._-]|$)/.test(n))return'en';return'en'}
async function attachSubtitle(file,label=file.name){if(!S.media||S.kind!=='video')return null;let entry={file,label,track:null,url:null};try{if(/\.vtt$/i.test(file.name)){const txt=await file.text(),blob=new Blob([txt],{type:'text/vtt'}),u=URL.createObjectURL(blob),track=document.createElement('track');track.kind='subtitles';track.label=label;track.srclang=guessLang(file.name);track.src=u;track.default=false;e.video.appendChild(track);entry.url=u;await new Promise(r=>setTimeout(r,100));entry.track=track.track;track.addEventListener('load',()=>{captureSubtitleTiming(entry.track);updateSubtitleSyncUI()},{once:true})}else{const cues=parseSRT(await file.text()),track=e.video.addTextTrack('subtitles',label,guessLang(file.name));track.mode='disabled';cues.forEach(c=>{try{track.addCue(new VTTCue(c.a,c.b,c.t))}catch{}});entry.track=track}if(entry.track?.cues)captureSubtitleTiming(entry.track);S.subtitles.push(entry);return entry}catch{return null}}
function escapeHTML(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderSubtitleFiles(){}
function applySubtitle(i){const s=S.subtitles[i];if(!s?.track)return;[...e.video.textTracks].forEach(t=>t.mode='disabled');s.track.mode='showing';S.cc=s.label;S.activeSubtitle=s;S.subtitleOffset=0;showMode('Captions',s.label,'CC+');updateSubtitleSyncUI()}
function chooseTrack(tracks){return tracks.find(t=>/sinhala|sin|\bsi\b/i.test(t.language+' '+t.label))||tracks.find(t=>/tamil|tam|\bta\b/i.test(t.language+' '+t.label))||tracks.find(t=>/english|eng|\ben\b/i.test(t.language+' '+t.label))||tracks[0]}
async function autoCC(){if(S.kind!=='video')return false;let embedded=[...e.video.textTracks].filter(t=>t.kind==='subtitles'||t.kind==='captions');if(embedded.length){[...e.video.textTracks].forEach(t=>t.mode='disabled');const preferred=chooseTrack(embedded);preferred.mode='showing';S.activeSubtitle=S.subtitles.find(s=>s.track===preferred)||{track:preferred,label:preferred.label||preferred.language||'Embedded'};S.subtitleOffset=0;captureSubtitleTiming(preferred);updateSubtitleSyncUI();showMode('Captions','Auto · '+(preferred.label||preferred.language||'Embedded'),'CC+');return true}const base=(S.files.find(f=>kind(f)==='video')?.name||'').replace(/\.[^.]+$/,'').toLowerCase();const candidates=S.files.filter(f=>kind(f)==='subtitle'&&f.name.toLowerCase().startsWith(base));if(candidates.length){for(const f of candidates)if(!S.subtitles.some(s=>s.file===f))await attachSubtitle(f,f.name);const pref=S.subtitles.find(s=>/\.si\.|_si\.|-si\.|sinhala/i.test(s.file.name))||S.subtitles.find(s=>/\.ta\.|_ta\.|-ta\.|tamil/i.test(s.file.name))||S.subtitles.find(s=>/\.en\.|_en\.|-en\.|english/i.test(s.file.name))||S.subtitles[0];applySubtitle(S.subtitles.indexOf(pref));return true}return false}
async function addSubtitleFiles(files){if(S.kind!=='video'){showMode('Captions','Open a video first','CC');return}for(const f of files.filter(f=>kind(f)==='subtitle'))if(!S.subtitles.some(s=>s.file===f))await attachSubtitle(f,f.name);if(S.subtitles.length){applySubtitle(S.subtitles.length-1);showMode('Captions','Loaded · '+S.subtitles[S.subtitles.length-1].label,'CC');updateLabels()}}
async function cycleCC(){if(S.kind!=='video'){showMode('Captions','Video only','CC');return}const tracks=[...e.video.textTracks].filter(t=>t.kind==='subtitles'||t.kind==='captions'),all=S.subtitles.map(s=>s.track).filter(Boolean),pool=[...all,...tracks.filter(t=>!all.includes(t))];if(!pool.length){const found=await autoCC();if(found)return;showMode('Captions','Load a subtitle file','CC');e.subInput.click();return}let current=-1;if(S.cc!=='off'){current=pool.findIndex(t=>t.mode==='showing')}if(current<pool.length-1){const next=pool[current+1];[...e.video.textTracks].forEach(t=>t.mode='disabled');next.mode='showing';S.cc=next.label||next.language||'Captions';S.activeSubtitle=S.subtitles.find(s=>s.track===next)||null;S.subtitleOffset=0;showMode('Captions',S.cc,'CC+');updateSubtitleSyncUI();return}[...e.video.textTracks].forEach(t=>t.mode='disabled');S.cc='off';S.activeSubtitle=null;S.subtitleOffset=0;e.subtitleSync?.classList.add('hidden');showMode('Captions','Off','CC+')}

function setSound(mode){S.audio=mode;updateLabels();if(!S.media||!['video','audio'].includes(S.kind))return;if(S.iosNative){S.media.volume=mode==='original'?1:mode==='enhanced'?1:mode==='cinema'?1:1;showMode('Sound',mode==='original'?'Original · device audio':mode==='enhanced'?'Enhanced · device-safe':mode==='cinema'?'Cinema · device-safe':'Spatial · device-safe',mode==='spatial'?'◌':'◉');return}if(mode==='original'){const g=currentSource();if(g){routeAudio('original');S.audioCtx?.resume().catch(()=>{})}S.media.volume=1;showMode('Sound','Original · untouched','◉');return}const g=ensureAudioGraph(S.media);if(!g){showMode('Sound','Enhancement unavailable','!');return}routeAudio(mode);showMode('Sound',{enhanced:'Enhanced · Loudness + clarity',cinema:'Cinema · bass + presence',spatial:'Spatial · wider presence'}[mode],mode==='spatial'?'◌':'◉')}
function cycleSound(){const a=['original','enhanced','cinema','spatial'],n=a[(a.indexOf(S.audio)+1)%a.length];setSound(n)}
function qualityFilter(n){return{original:'none',natural:'contrast(1.05) saturate(1.06)',enhanced:'contrast(1.12) saturate(1.14) brightness(1.02) sharpen(0)',ultra:'contrast(1.18) saturate(1.18) brightness(1.03)'}[n]||'none'}
function cycleVideo(){const a=['original','natural','enhanced','ultra'],n=a[(a.indexOf(S.video)+1)%a.length];S.video=n;updateLabels();if(S.kind==='video')e.video.style.filter=qualityFilter(n);showMode('Video Quality',{original:'Original Quality',natural:'Natural',enhanced:'Enhanced Quality',ultra:'Ultra Quality'}[n],'◇')}
function updateLabels(){const sl={original:'Original',enhanced:'Enhanced',cinema:'Cinema',spatial:'Spatial'}[S.audio]||'Original',vl={original:'Original Quality',natural:'Natural',enhanced:'Enhanced Quality',ultra:'Ultra Quality'}[S.video]||'Original Quality';e.sound.querySelector('span:last-child').textContent=`Sound · ${sl}`;e.picture.querySelector('span:last-child').textContent=`Video Quality · ${vl}`;updateSpeedLabel();updateTransportLabels()}
function updateSpeedLabel(){const t=`${S.playbackRate}×`;e.speedTopLabel.textContent=t}
function cycleSpeed(){const rates=[.5,.75,1,1.25,1.5,1.75,2],n=rates[(rates.indexOf(S.playbackRate)+1)%rates.length];S.playbackRate=n;if(S.media&&!S.remote)S.media.playbackRate=n;updateSpeedLabel();showMode('Playback Speed',`${n}×`,'▶')}
function cycleFrame(){if(S.kind!=='video'){showMode('Screen Width','Video only','↔');return}const a=['original','fit','fill','wide'],n=a[(a.indexOf(S.fit)+1)%a.length];S.fit=n;applyFrame();showMode('Screen Width',{original:'Original',fit:'Fit Screen',fill:'Fill Screen',wide:'Wide'}[n],'↔')}
function updateTransportLabels(){if(!e.repeatLabel)return;const map={off:'Repeat Off',one:'Repeat Once',track:'Repeat Track',all:'Repeat All'};e.repeatLabel.textContent=map[S.repeat]||'Repeat Off';e.repeat.classList.toggle('active',S.repeat!=='off')}
function cycleRepeat(){const a=['off','one','track','all'];S.repeat=a[(a.indexOf(S.repeat)+1)%a.length];S.repeatOnceUsed=false;updateTransportLabels();showMode('Repeat',({off:'Off',one:'Once',track:'Track',all:'All'})[S.repeat],'↻')}
function stopPlayback(){if(!S.media||S.remote)return;S.media.pause();try{S.media.currentTime=0}catch{};showControls();showMode('Playback','Stopped','■')}
function loadQueueIndex(i){if(!S.queue.length)return;const len=S.queue.length;S.queueIndex=(i+len)%len;const file=S.queue[S.queueIndex];clearCurrentMedia();S.kind=kind(file);S.media=S.kind==='video'?e.video:S.kind==='audio'?e.audio:e.image;e.audioVisual?.classList.toggle('hidden',S.kind!=='audio');e.audioVisual?.setAttribute('aria-hidden',S.kind!=='audio');if(S.kind==='audio'&&e.audioTitle)e.audioTitle.textContent=file.name.replace(/\.[^.]+$/,'');setMediaSessionMetadata(file.name.replace(/\.[^.]+$/,''));e.player.classList.remove('hidden');e.player.setAttribute('aria-hidden','false');e.welcome.classList.add('hidden');showPreparing();enableAllControls();S.url=URL.createObjectURL(file);if(S.kind==='image'){e.image.src=S.url;e.image.classList.remove('hidden');e.image.onload=()=>{hidePreparing();e.topActions.classList.remove('hidden')};return}S.media.src=S.url;S.media.classList.remove('hidden');e.empty.classList.add('hidden');S.media.playbackRate=S.playbackRate;S.media.addEventListener('loadedmetadata',async()=>{hidePreparing();sync();const subs=S.files.filter(f=>kind(f)==='subtitle');for(const f of subs)await attachSubtitle(f,f.name);await autoCC();updateControlCapabilities();updateLabels();captureBackdrop();setTimeout(()=>autoLandscape(),80);if(S.kind==='video'||S.kind==='audio')S.media.play().catch(()=>{})},{once:true});S.media.addEventListener('error',()=>{hidePreparing();showMode('Media','Format or codec unavailable','!')},{once:true});S.media.load();updateQueueButtons()}
function previousTrack(){if(S.queue.length>1){loadQueueIndex(S.queueIndex-1)}else if(S.media){S.media.currentTime=0;showMode('Previous','Start of track','◀')}}
function nextTrack(){if(S.queue.length>1){loadQueueIndex(S.queueIndex+1)}else{showMode('Next','No next item loaded','▶')}}


function updateQueueButtons(){if(!e.prev)return;const multi=S.queue.length>1;e.prev.disabled=!multi;e.next.disabled=!multi;e.repeat.disabled=!S.media&&!S.queue.length}
async function fullscreen(){try{if(document.fullscreenElement){await document.exitFullscreen();return}if(e.shell.requestFullscreen){await e.shell.requestFullscreen();return}if(S.kind==='video'&&e.video.webkitEnterFullscreen){e.video.webkitEnterFullscreen();return}}catch{}showMode('Fullscreen','Browser controlled','⛶')}
async function pip(){if(S.remote){showMode('PiP','Use the embedded player controls','▣');return}if(S.kind!=='video'){showMode('PiP','Video only','▣');return}try{if(document.pictureInPictureElement){await document.exitPictureInPicture();return}if(typeof e.video.webkitSupportsPresentationMode==='function'&&e.video.webkitSupportsPresentationMode('picture-in-picture')&&typeof e.video.webkitSetPresentationMode==='function'){e.video.webkitSetPresentationMode('picture-in-picture');return}if(document.pictureInPictureEnabled&&typeof e.video.requestPictureInPicture==='function'){await e.video.requestPictureInPicture();return}}catch{}showMode('PiP','Unavailable in this browser','▣')}
function updateControlCapabilities(){const video=S.kind==='video'&&!S.remote;const pipOK=video&&((typeof e.video.webkitSupportsPresentationMode==='function'&&e.video.webkitSupportsPresentationMode('picture-in-picture'))||(document.pictureInPictureEnabled&&typeof e.video.requestPictureInPicture==='function'));e.pip.disabled=!pipOK;e.pip.classList.toggle('unsupported',!pipOK);e.pip.title=pipOK?'Picture in Picture':'PiP unavailable here';e.full.disabled=!(document.fullscreenEnabled||typeof e.video.webkitEnterFullscreen==='function');if(e.loadSub)e.loadSub.disabled=!video}
function scheduleControlsHide(){clearTimeout(S.controlsTimer);S.controlsTimer=setTimeout(()=>{if(S.media&&!S.media.paused)e.shell.classList.add('controls-hidden')},2600)}
function showControls(){clearTimeout(S.controlsTimer);e.shell.classList.remove('controls-hidden')}
function playerPointer(){showControls();if(S.media&&!S.media.paused)scheduleControlsHide()}

function captureBackdrop(){if(S.kind!=='video'||S.remote)return;try{if(!e.video.videoWidth||!e.video.videoHeight)return;const c=document.createElement('canvas');c.width=640;c.height=Math.round(640*e.video.videoHeight/e.video.videoWidth);const ctx=c.getContext('2d');ctx.drawImage(e.video,0,0,c.width,c.height);const u=c.toDataURL('image/jpeg',.72);e.backdrop.style.backgroundImage=`linear-gradient(135deg,rgba(4,18,28,.64),rgba(10,20,43,.32)),url(${u})`}catch{}}
function showPreparing(){e.prep.classList.remove('hidden');e.empty.classList.add('hidden');e.topActions.classList.add('hidden');e.shell.classList.remove('controls-hidden')}
function hidePreparing(){e.prep.classList.add('hidden');e.topActions.classList.remove('hidden')}

function providerFromUrl(raw){let u;try{u=new URL(raw)}catch{return null}const h=u.hostname.toLowerCase().replace(/^www\./,'');if(h==='youtube.com'||h==='m.youtube.com'||h==='youtu.be'){let id=u.searchParams.get('v');if(!id&&h==='youtu.be')id=u.pathname.split('/').filter(Boolean)[0];if(!id){const m=u.pathname.match(/\/(?:shorts|embed)\/([^/?]+)/);id=m?.[1]}return id?{provider:'youtube',url:`https://www.youtube-nocookie.com/embed/${encodeURIComponent(id)}?autoplay=1&playsinline=1&rel=0&cc_load_policy=0&enablejsapi=1`}:null}if(h==='tiktok.com'||h==='vm.tiktok.com'){const m=u.pathname.match(/\/video\/(\d+)/);if(m)return{provider:'tiktok',url:`https://www.tiktok.com/player/v1/${m[1]}?controls=1&progress_bar=1&play_button=1&volume_control=1&fullscreen_button=1&timestamp=1&closed_caption=1`}}if(h==='facebook.com'||h==='fb.watch'){return{provider:'facebook',url:`https://www.facebook.com/plugins/video.php?href=${encodeURIComponent(raw)}&show_text=0&width=960`}}return null}
function isDirectMediaUrl(raw){try{const u=new URL(raw);return /\.(mp4|m4v|webm|mov|ogv|m3u8|mp3|wav|flac|m4a|aac|ogg|opus)(?:$|[?#])/i.test(u.pathname+u.search)}catch{return false}}
function playRemote(raw){clean();const p=providerFromUrl(raw);S.remote=true;S.remoteUrl=raw;S.remoteProvider=p?.provider||null;S.kind='remote';S.files=[];setMediaSessionMetadata('Foldrone Play');e.player.classList.remove('hidden');e.player.setAttribute('aria-hidden','false');e.welcome.classList.add('hidden');showPreparing();setTimeout(()=>{hidePreparing();e.remote.classList.remove('hidden');const iframe=document.createElement('iframe');iframe.src=p?p.url:raw;iframe.title='Foldrone Play public video';iframe.allow='autoplay; fullscreen; picture-in-picture; encrypted-media; web-share';iframe.allowFullscreen=true;iframe.referrerPolicy='strict-origin-when-cross-origin';e.remote.replaceChildren(iframe);e.topActions.classList.remove('hidden');e.pip.disabled=true;e.fit.disabled=true;e.speedTop.disabled=true;updateControlCapabilities();showMode('Public URL',p?`${p.provider[0].toUpperCase()+p.provider.slice(1)} player`:'Embedded player','↗')},550)}
function mediaTitle(){
  if(S.queue?.length&&S.queue[S.queueIndex]) return S.queue[S.queueIndex].name.replace(/\.[^.]+$/,'');
  if(S.remoteUrl){try{return new URL(S.remoteUrl).hostname.replace(/^www\./,'')}catch{}}
  return S.kind==='video'?'Current video':'Current media';
}
function openSubtitleModal(){
  if(S.kind!=='video'){showMode('Subtitles','Open a video first','CC');return}
  e.subtitleProviders.classList.add('hidden');
  e.subtitleModal.classList.remove('hidden');
}
function closeSubtitleModal(){e.subtitleModal.classList.add('hidden')}
function openOnlineSubtitleProvider(){
  e.subtitleProviders.classList.remove('hidden');
  showMode('Subtitles','Choose a provider for '+mediaTitle(),'CC');
}
function openUrlModal(){e.urlModal.classList.remove('hidden');setTimeout(()=>e.urlInput.focus(),40)}
function closeUrlModal(){e.urlModal.classList.add('hidden')}
function submitUrl(){const raw=e.urlInput.value.trim();if(!raw){showMode('Public URL','Paste a video URL','↗');return}if(!/^https?:\/\//i.test(raw)){showMode('Public URL','Use an http(s) URL','!');return}closeUrlModal();e.urlInput.value='';if(isDirectMediaUrl(raw)){openRemoteDirect(raw)}else if(providerFromUrl(raw)){playRemote(raw)}else{playRemote(raw)}}
async function loadHlsLibrary(){if(window.Hls)return window.Hls;return await new Promise((resolve,reject)=>{const sc=document.createElement('script');sc.src='https://cdn.jsdelivr.net/npm/hls.js@1.7.3/dist/hls.min.js';sc.onload=()=>resolve(window.Hls);sc.onerror=reject;document.head.appendChild(sc)})}
async function openRemoteDirect(raw){clean();S.remote=false;S.remoteProvider='direct-url';const isAudio=/\.(mp3|wav|flac|m4a|aac|ogg|opus)(?:$|[?#])/i.test(raw);S.kind=isAudio?'audio':'video';S.url=raw;S.media=isAudio?e.audio:e.video;e.audioVisual?.classList.toggle('hidden',!isAudio);e.audioVisual?.setAttribute('aria-hidden',!isAudio);if(isAudio&&e.audioTitle)e.audioTitle.textContent='Online Audio';setMediaSessionMetadata(isAudio?'Online Audio':'Online Video');e.player.classList.remove('hidden');e.player.setAttribute('aria-hidden','false');e.welcome.classList.add('hidden');showPreparing();enableAllControls();e.video.src='';e.audio.src='';S.media.src=raw;S.media.classList.remove('hidden');e.empty.classList.add('hidden');const isHls=/\.m3u8(?:$|[?#])/i.test(raw);if(S.kind==='video'&&isHls&&!e.video.canPlayType('application/vnd.apple.mpegurl')){try{const HlsCtor=await loadHlsLibrary();if(HlsCtor?.isSupported()){const hls=new HlsCtor({enableWorker:true,lowLatencyMode:true});S.hls=hls;hls.loadSource(raw);hls.attachMedia(e.video)}else{e.video.src=raw}}catch{e.video.src=raw}}else{S.media.src=raw}S.media.load();S.media.addEventListener('loadedmetadata',async()=>{hidePreparing();e.topActions.classList.remove('hidden');updateControlCapabilities();updateLabels();captureBackdrop();showMode('Public URL',isHls?'Direct HLS stream':isAudio?'Direct audio':'Direct video','↗');if(S.kind==='audio')S.media.play().catch(()=>{})},{once:true});S.media.addEventListener('error',()=>{hidePreparing();showMode('Public URL','This URL cannot be played directly','!')},{once:true})}
async function openFiles(files){files=[...files];const mediaFiles=files.filter(f=>['video','audio','image'].includes(kind(f))),subs=files.filter(f=>kind(f)==='subtitle');if(!mediaFiles.length){if(subs.length&&S.kind==='video'){S.files.push(...subs);await addSubtitleFiles(subs);return}return}clean();S.queue=mediaFiles;S.queueIndex=0;S.files=files;loadQueueIndex(0);updateQueueButtons()}
async function autoLandscape(){if(S.kind!=='video'||S.remote)return;if(innerWidth>innerHeight)e.shell.classList.add('landscape-cinema');else e.shell.classList.remove('landscape-cinema')}

function enableAllControls(){[e.loadSub,e.fit,e.speedTop,e.pip,e.full].forEach(b=>b.disabled=false);updateControlCapabilities()}


e.open.onclick=e.hero.onclick=openPicker;e.url.onclick=e.heroUrl.onclick=openUrlModal;e.urlClose.onclick=e.urlCancel.onclick=closeUrlModal;e.urlPlay.onclick=submitUrl;e.urlInput.addEventListener('keydown',ev=>{if(ev.key==='Enter')submitUrl();if(ev.key==='Escape')closeUrlModal()});e.subtitleClose.onclick=closeSubtitleModal;e.subtitleChoose.onclick=()=>{closeSubtitleModal();e.subInput.value='';e.subInput.click()};e.subtitleOnline.onclick=openOnlineSubtitleProvider;e.syncMinus1.onclick=()=>setSubtitleOffset(-1);e.syncMinus01.onclick=()=>setSubtitleOffset(-.1);e.syncReset.onclick=resetSubtitleOffset;e.syncPlus01.onclick=()=>setSubtitleOffset(.1);e.syncPlus1.onclick=()=>setSubtitleOffset(1);e.loadSub.onclick=()=>{openSubtitleModal();updateSubtitleSyncUI()};e.input.onchange=()=>openFiles([...e.input.files]);e.subInput.onchange=()=>addSubtitleFiles([...e.subInput.files]);
e.home.onclick=e.close.onclick=()=>{clean();e.player.classList.add('hidden');e.welcome.classList.remove('hidden');e.urlInput.value='';closeSubtitleModal()};e.play.onclick=()=>{if(!S.media||S.remote)return;if(S.media.paused)S.media.play().catch(()=>{});else S.media.pause()};e.stop.onclick=stopPlayback;e.prev.onclick=previousTrack;e.next.onclick=nextTrack;e.repeat.onclick=cycleRepeat;e.back.onclick=()=>{if(S.media&&!S.remote)S.media.currentTime=Math.max(0,S.media.currentTime-10)};e.forward.onclick=()=>{if(S.media&&!S.remote)S.media.currentTime=Math.min(S.media.duration||Infinity,S.media.currentTime+10)};e.mute.onclick=()=>{if(S.media&&!S.remote&&'muted'in S.media)S.media.muted=!S.media.muted};e.seek.oninput=()=>{if(S.media&&!S.remote)S.media.currentTime=+e.seek.value};e.sound.onclick=cycleSound;e.picture.onclick=cycleVideo;e.speedTop.onclick=cycleSpeed;e.pip.onclick=pip;e.full.onclick=fullscreen;e.fit.onclick=cycleFrame;
e.stage.addEventListener('touchend',ev=>{if(!S.media||S.remote||!['video','audio'].includes(S.kind))return;const t=ev.changedTouches?.[0];if(!t)return;const rect=e.stage.getBoundingClientRect();const x=t.clientX-rect.left;const w=rect.width;showControls();if(S.kind==='video'){if(x<w*.30){e.back.click();return}if(x>w*.70){e.forward.click();return}e.play.click();return}e.play.click()},{passive:true});
e.stage.addEventListener('click',ev=>{if(ev.target.closest('button,input,a'))return;if(!S.media||S.remote||!['video','audio'].includes(S.kind))return;const rect=e.stage.getBoundingClientRect(),x=ev.clientX-rect.left;if(S.kind==='video'){if(x<rect.width*.30)e.back.click();else if(x>rect.width*.70)e.forward.click();else e.play.click()}else e.play.click()});
e.shell.addEventListener('pointerdown',playerPointer,{passive:true});e.shell.addEventListener('mousemove',playerPointer,{passive:true});
addEventListener('resize',()=>{if(S.media&&S.kind==='video')autoLandscape()});addEventListener('orientationchange',()=>{if(S.media&&S.kind==='video')autoLandscape()});
addEventListener('keydown',ev=>{if(!S.media&&!S.remote)return;if(ev.code==='Space'){ev.preventDefault();e.play.click()}if(ev.key==='f')fullscreen();if(ev.key==='p')pip();if(ev.key==='c')cycleCC();if(ev.key==='s')cycleSpeed();if(ev.key==='m')e.mute.click();if(ev.key==='j')e.back.click();if(ev.key==='l')e.forward.click();if(ev.key==='k')e.play.click();if(ev.key==='Escape')closeUrlModal()});
updateLabels();updateTransportLabels();updateQueueButtons();
})();